### ISSUE TITLE
Cannot access class 'kotlinx.coroutines.experimental.Job'

### ISSUE THREAD

**Issue by Barddo** [brianmadden/krawler#22]
Thrown `Cannot access class 'kotlinx.coroutines.experimental.Job'. Check your module classpath for missing or conflicting dependencies` error by running on Kotlin 1.3.60, JVM 8.

**Comment by brianmadden** [comment]
Sorry, just saw this was posted. I'll take a look and see what's up.

**Comment by brianmadden** [comment]
@Barddo can you pull this branch and see if it works for you? https://github.com/brianmadden/krawler/tree/upgrade_packages

**Comment by Barddo** [comment]
Cool! Everything is pretty fine here.

**Comment by brianmadden** [comment]
Great, I'll get this merged into master then. Thanks!
